language: node_js
node_js:
  - node
  - 10
  - 8
cache: npm
# Developers do not need coveralls installed locally while developing. So
# there's no great benefit to adding it to devDependencies. Instead, we install
# it here.
before_script: npm i --no-save coveralls
after_success: npm run coverage
